Feature/post song to pinata
Wbebey/dwaves pull request #29
Opened 2022-11-24 19:28 UTC by TharickABDUL

## What & How
Create the route to pin the music and the cover to IPFS with the metadata

## Tickets
* The link to the issue/ticket: _#35yc9ec[CODE REVIEW]_

2022-11-24 19:28 UTC, Wbebey commented
Task linked: [CU-35yc9ec Can POST a song in Pinata](https://app.clickup.com/t/35yc9ec)

2022-11-24 21:47 UTC, alexandre-pinon requested changes
See review

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        }
On verra ensemble quand je mergerai ma branche mais j'ai mis en place tout un système pour la validation et la gestion d'erreurs.
Pour le moment garde comme ça

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        let music: any = req.files.music
t'as pas trouvé le type finalement ?

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        console.log('cover : ', cover.name, ' - coverCID : ', coverCID)
pas de console log dans les pr, sinon utilise mon logger pour les log non temporaires

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        console.log('music : ', music.name, ' - musicCID : ', musicCID)
pas de console log dans les pr, sinon utilise mon logger pour les log non temporaires

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        const coverCID = await pinataService.pinFileToIPFS(fs.createReadStream('./src/services/uploadsFile/' + cover.name), {type: 'cover'})
pas fan des chemins en dur mais bon. Au moins créer une variable ici tu copie colle le path + cover.name

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        const musicCID = await pinataService.pinFileToIPFS(fs.createReadStream('./src/services/uploadsFile/' + music.name), musicMetadata)
pas fan des chemins en dur mais bon. Au moins créer une variable ici tu copie colle le path + cover.name

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +        fs.rmSync('./src/services/uploadsFile/', {recursive: true});
encore une fois stocker dans une variable le path

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/interfaces/services.interface.ts
> +}
ça bougera dans le dossier types mais on le fera plus tard au pire

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/interfaces/services.interface.ts
> +// }
pas de comm dans les PR batard !

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/routers/album.router.ts
> +const albumController = new AlbumController()
bouge le new dans album.controller.ts et fait un export default
genre : 
```
const albumController = new AlbumController()
export default albumController
```

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/routers/app.router.ts
> +import PinataRouter from './music.router'
import avec @routers/*** plutot que ./***

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/routers/app.router.ts
> +appRouter.use('/music', PinataRouter)
music**s**

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/routers/music.router.ts
> +const musicController = new MusicController()
même remarque met le new dans music.controller.ts et export default

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +}
ça bougera dans types/ mais on peut le faire tard plus

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +        data.append('pinataOptions', pinataOptions);
tej ça si c'est optionnel

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +    //async function pinFileToIPFS(file: fs.ReadStream, metadata: Metadata) {
remove commentaire

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/smart-contracts/contracts/ArtistPayer.sol
>  }
t'es pas censé avoir ces changements: rebase sur staging c'est mes commits batard !

2022-11-24 21:47 UTC, alexandre-pinon commented on backend/smart-contracts/hardhat.config.ts
> +// @ts-ignore
pk ts-ignore ?

2022-11-25 00:59 UTC, alexandre-pinon approved these changes
Ok pour l'api, pour les contrats on verra quand tu feras ta pr avec les routes nft je pense y aura 2, 3 trucs a revoir

2022-11-25 09:35 UTC, merged