Feature/get music from pinata
Wbebey/dwaves pull request #45
Opened 2022-12-01 15:39 UTC by TharickABDUL

## What & How
* Can get all musics from Pinata 
* and can filter by genre 

## Tickets
* Ticket : [CI-3640jue](https://app.clickup.com/t/3640jue)

2022-12-02 10:32 UTC, alexandre-pinon requested changes
:raised_eyebrow:

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +      url = `${env.pinataApiHost}/data/pinList?status=pinned&metadata[keyvalues][type]={"value":"music","op":"eq"}`
Tu te répète pour R.
Fais plutot : 
```
const baseUrl = ${env.pinataApiHost}/data/pinList?status=pinned&metadata[keyvalues]
const filter = {"type":{"value":"music","op":"eq"}}
const genreFilter = {...filter, "genreId" : {"value" : query.genre!.id, "op": "eq"}}
const url = genre ? ${baseUrl}=${genreFilter} : ${baseUrl}=${filter}
```
on pourra réutiliser baseUrl dans d'autres query donc potentiemment le mettre en attribut de PinataService a voir

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +    let musicsByGenre: MusicWithMetadata[] = []
Préfère mettre le type dans la fonction axios : `axios.get<PinataGetResponse[]>`

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +    }
Alors oui mais non si on fait un get all on va faire autant de requete en base qu'on a de musique. Il faut limiter au maximum et parallèliser les query avec les promesses, un truc du style :
```
const artistIds = [... new Set(musicsFromPinata.map((music) => music.metadata.keyvalues.artistId))]
await userService.findMany({id: { in: artistIds}})
```
la même chose pour les album et les genre (le new Set permet d'avoir que les valeurs unique du tableau des Id)
comme ça peut import le nombre de musique a query on fait que 3 requêtes en base max

et pareil pour init `musicsByGenre` (pas fan du nom vu que la query est pas forcément par genre) tu peux le faire via un map sur `musicsFromPinata`

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +  listenings: number
musicName -> name
musicUrl -> url ou src
album -> albumName
artist -> artistName
coverUrl -> cover

histoire de pas confondre les champs avec les entités en base

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +export type MusicWithMetadata = {
Pas trop fan du nom, trop proche de MusicMetadata, peut être un truc du genre ViewMusic ?

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +}
genre?: Prisma.Genre
le sanitizer te renvoi l'object DB direct dans req.query normalement

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +export type PinataGetResponse = {
PinataPinListResponse pour rester cohérent avec la route

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/validators/album.validator.ts
> +import {AppValidator} from '@validators/app.validator'
wsh d'où tu vires mes espaces entre les crochets ??

2022-12-02 10:32 UTC, alexandre-pinon commented on backend/api/src/validators/album.validator.ts
> +      throw new AppError('Invalid genre', status)
trop clean (on se demande qui a codé ça :thinking: )

2022-12-02 16:15 UTC, alexandre-pinon requested changes
:|

2022-12-02 16:15 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +
delete

2022-12-02 16:15 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +
utilise un for (music of res.data.rows) pour loop qu'une fois au lieu de 3

2022-12-02 16:15 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +        artistName: artists.find(x => x.id === music.metadata.keyvalues.artistId)!.username,
JUSTE au cas zou : `albums.find(x => x.id === music.metadata.keyvalues.albumId)?.name || ''` pour gérer le cas obscur où il trouve pas les entités correspondantes en base et rien faire crash côté front

2022-12-02 16:15 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +  genre?: Genre | null
pas besoin de '| null' si tu met un ? dans la definition

2022-12-02 16:15 UTC, alexandre-pinon commented on backend/api/src/types/pinata.type.ts
> +type MusicWithMetadata = {
PinataMusic ou MusicIPFS ?

2022-12-02 21:05 UTC, TharickABDUL commented on backend/api/src/services/pinata.service.ts
> +    const genres = genre ? queryArray : await genreService.findMany({id: { in: genreIds}})
incroyable !!

2022-12-03 12:34 UTC, alexandre-pinon approved these changes
Pas mal pas mal

2022-12-03 12:40 UTC, merged