Feature/post album on pinata
Wbebey/dwaves pull request #53
Opened 2022-12-04 01:35 UTC by TharickABDUL

## What & How
* can Pin an Album

## Tickets
* Ticket : [CU-#3cc7vk6](https://app.clickup.com/t/3cc7vk6)

2022-12-05 07:32 UTC, alexandre-pinon requested changes
Hey Hey 🙂

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/validators/music.validator.ts
>        }
gaffe à l'indentation sinon ok

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/services/pinata.service.ts
> +    data.append('pinataMetadata',  metadataPinata)
je préfère ne pas rajouter de paramètre à la fonction et passer le name dans les metadata. Sur ipfs on garde le nom de fichier original et on viendra query sur les metadata

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +    })
si tu regardes c'est exactement le même code que pour `uploadSingle`. ça devrait faire *ding* -> j'exporte dans une fonction/méthode.
Ce qui serait pas ce serait d'export ça dans la méthode `create` de `albumService` en lui passant `cover` et `type` en paramètre et en retournant l'object `album` (dont tu as besoin après)
Du coup modif ça sur `uploadSingle` aussi

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/routers/music.router.ts
> +        .bail(),
je rajouterai une validation sur le champs : voir si c'est bien un tableau de string, pour ça tu peux utiliser les fonctions JS `JSON.parse()` et `isArray()` dans un validator

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +    const musicsNameArray = musicsName.split(',');
de manière générale on évite la manipulation de string comme ça, il vaut mieux parse les strings en objets (cf. mon commentaire sur `music.router`)
avec le sanitizer tu pourra recup direct l'objet : `const musicNames = req.body.musicNames`
et tu pourras même destructurer avec les lignes du haut pour avoir : `const { genre, albumName, musicNames } = req.body`
(attention a bien modif genreId en genre.id !)

2022-12-05 07:32 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +    res.json({coverUrl, musicsUrl})
excellent le `await Promise.all(musics.map` ça permet de loop en parallèle ce qui n'est pas le cas des boucle `for` !
attention par contre `musicMetadata` n'as pas besoin d'être dans le map vu qu'il n'utilise aucun paramètre
au niveau du return je pense que c'est mieux de se limiter à `${env.pinataGatewayHost}/${musicCID}` pour le front ce sera plus simple à manipuler

2022-12-05 20:01 UTC, TharickABDUL commented on backend/api/src/controllers/user.controller.ts
> +import {RequestHandler} from "express";
c'est pas moi c'est webstorm ...

2022-12-05 20:05 UTC, TharickABDUL commented on backend/api/src/interfaces/validator.interface.ts
> +import {RequestHandler} from 'express'
webstorm ... 😨

2022-12-06 08:57 UTC, TharickABDUL commented on backend/api/src/controllers/music.controller.ts
> +    })
et du coup je dois faire une nouvelle methode dans `albumService` qui prend en entrée cover et type et dans cette méthode je vais pin la cover et créer un album et je vais retourner l'album créé ? ou je modifie le create de `albumService` stp

2022-12-06 08:57 UTC, TharickABDUL commented on backend/api/src/validators/music.validator.ts
>        }
mais du coup il y a un problème avec l'indentation ? 😨

2022-12-06 11:09 UTC, Wbebey commented
Task linked: [CU-3cc7vk6 Can POST an album](https://app.clickup.com/t/3cc7vk6)

2022-12-06 15:21 UTC, alexandre-pinon commented on backend/api/src/controllers/music.controller.ts
> +    })
pour le moment on va partir du principe que l'on pin une cover à chaque création d'album donc ouais modifie la fonction create de `albumService` avec ce qui a été dit plus haut

2022-12-07 14:55 UTC, alexandre-pinon approved these changes
LGTM

2022-12-07 14:55 UTC, merged